# Generated by Django 6.1 on 2026-08-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_folder_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookmarks.folder'),
        ),
    ]
